In [1]:
x = 3

print(x)

3


In [2]:
x

3

In [3]:
3 > 5

False

In [4]:
4 == 5

False

In [5]:
4 == 4

True

In [6]:
10 % 1

0

In [7]:
10 % 3

1

In [8]:
type("Hell")

str

In [9]:
range (5, 10)

range(5, 10)

In [10]:
type(range(5, 10))

range

In [11]:
list(range(5, 10))

[5, 6, 7, 8, 9]

In [12]:
list(range(5))

[0, 1, 2, 3, 4]

In [13]:
things = ["Apple", "Grape", 101, "Onion", False]

In [14]:
things

['Apple', 'Grape', 101, 'Onion', False]

In [15]:
things[0]

'Apple'

In [16]:
things[-1]

False

In [17]:
things[:-1]

['Apple', 'Grape', 101, 'Onion']

In [18]:
type(things[2])

int

In [19]:
type(things[3])

str

In [20]:
type(things[4])

bool

In [21]:
list(range(11,16))

[11, 12, 13, 14, 15]

In [22]:
sum([1, 2, 3])

6

In [23]:
numbers = [19, 4, 33, 6]

In [24]:
numbers.sort()

In [25]:
numbers

[4, 6, 19, 33]

In [26]:
numbers.pop()

33

In [27]:
numbers

[4, 6, 19]

In [28]:
numbers.append(5)

In [29]:
numbers

[4, 6, 19, 5]

In [30]:
numbers

[4, 6, 19, 5]

In [31]:
numbers.remove(5)

In [32]:
numbers

[4, 6, 19]

In [33]:
numbers.append([7, 3, 99])

In [34]:
numbers

[4, 6, 19, [7, 3, 99]]

In [35]:
numbers.remove([7, 3, 99])

In [36]:
numbers.extend([7, 3, 99])

In [37]:
numbers

[4, 6, 19, 7, 3, 99]

In [38]:
primes = [1, 2 , 3, 5, 7]

In [39]:
primes

[1, 2, 3, 5, 7]

In [40]:
primes.remove(1)

In [41]:
primes

[2, 3, 5, 7]

In [42]:
primes.extend([11, 13, 17])

In [43]:
primes

[2, 3, 5, 7, 11, 13, 17]

In [44]:
primes.reverse()

In [45]:
primes

[17, 13, 11, 7, 5, 3, 2]

In [46]:
person = {
    "name":"Doug",
    "age": 33
}

person

{'name': 'Doug', 'age': 33}

In [47]:
person["name"]

'Doug'

In [48]:
person.keys()

dict_keys(['name', 'age'])

In [49]:
person.values()

dict_values(['Doug', 33])

In [50]:
person.items()

dict_items([('name', 'Doug'), ('age', 33)])

In [51]:
len(person)

2

In [52]:
student_info = {
    "Agnes" : 68, 
    "Bobby" : 45, 
    "Charlie" : {"age": 33, "gender": "Female"}
}

In [53]:
student_info

{'Agnes': 68, 'Bobby': 45, 'Charlie': {'age': 33, 'gender': 'Female'}}

In [54]:
student_info["Charlie"]["age"]

33

In [55]:
len(student_info)

3

In [56]:
person.update({"name": "Doug Sloan", "favourite fruit": ["pineapple", "watermelon"]})
person.pop("age")

33

In [57]:
person

{'name': 'Doug Sloan', 'favourite fruit': ['pineapple', 'watermelon']}

In [58]:
countries = {
    "uk": {
        "capital": "London", 
        "population": 1000
    },
    "germany": {
        "capital": "Berlin",
        "population": 5
    }
}

print(countries)

{'uk': {'capital': 'London', 'population': 1000}, 'germany': {'capital': 'Berlin', 'population': 5}}


In [59]:
german_population = countries["germany"] ["population"]

# Control flow and loops

In [60]:
temperature = 28
if temperature > 20:
    print("Heatwave warning!")

Heatwave warning!


In [61]:
temperature = 16
if temperature > 20:
    print("Heatwave warning!")
elif temperature < 10:
    print("The usual")
else:
    print("Perfect")

Perfect


In [62]:
animal = "chicken"

if animal == "chicken":
    print("My favourite animal")
else: 
    print("Sad, not my favourite animal")

My favourite animal


In [63]:
numbers = [1, 2, 3, 4]

for number in numbers:
    print(number * 2)

2
4
6
8


In [64]:
person

{'name': 'Doug Sloan', 'favourite fruit': ['pineapple', 'watermelon']}

In [65]:
person.update({"age":33})

In [66]:
person

{'name': 'Doug Sloan',
 'favourite fruit': ['pineapple', 'watermelon'],
 'age': 33}

In [67]:
for value in person.values():
    print(value)

Doug Sloan
['pineapple', 'watermelon']
33


In [68]:
numbers = [1, 6, 2, 2, 7, 1, 6 , 13, 99, 7]

even_numbers = []
for number in numbers:
    if number %2 == 0:
        even_numbers.append(number)
        
print(even_numbers)

[6, 2, 2, 6]


In [69]:
fz_bz_start_numbers = list(range(1, 101))

In [70]:
fz_bz_numbers = range(1, 101)
for number in fz_bz_numbers:
    if number %5 == 0 and number%3 == 0:
        print("FizzBuzz")
    elif number %3 == 0: 
        print("Fizz")
    elif number %5 == 0:
        print("Buzz")
    else:
        print(number)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [71]:
numbers = [1, 2, 3, 4]
numbers_squared = []

for number in numbers:
    numbers_squared.append(number*number)

In [72]:
numbers_squared

[1, 4, 9, 16]

In [73]:
numbers_squared = [number * number for number in numbers]

In [74]:
numbers_squared

[1, 4, 9, 16]

In [75]:
multiples_of_12 = []

for number in range(101):
    
    if number % 12 == 0:
        multiples_of_12.append(number)
        
multiples_of_12

[0, 12, 24, 36, 48, 60, 72, 84, 96]

In [76]:
[number for number in range(101) if number % 12 == 0]

[0, 12, 24, 36, 48, 60, 72, 84, 96]

In [77]:
words = ["apple", "orange", "dragon fruit"]

length_of_words = {word:len(word) for word in words}

length_of_words

{'apple': 5, 'orange': 6, 'dragon fruit': 12}

In [78]:
primes = [i for i in range(2, 100) if i % 2 != - 0 and i %3 != 0 and i % 5 != 0 and 7 != 0 and i % 11 != 0]

In [79]:
primes

[7,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 49,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 91,
 97]

In [80]:
ordinal_dict = {number: str(number) + "th" for number in range(4, 11)}

In [81]:
ordinal_dict

{4: '4th', 5: '5th', 6: '6th', 7: '7th', 8: '8th', 9: '9th', 10: '10th'}

In [82]:
def greet():
    print("Hey!")

In [83]:
greet()

Hey!


In [84]:
def greet():
    return "Hey"

In [85]:
greet()

'Hey'

In [86]:
greeting = greet()
print(greeting)

Hey


In [90]:
def greet(name):
    return "Hey " + name

In [92]:
greeting = greet("Doug")
print(greeting)

Hey Doug


In [95]:
def greet(name, time_of_day):
    return "Good " + time_of_day + ", " + name

In [96]:
greeting = greet("Doug", "morning")
print(greeting)

Good morning, Doug


In [102]:
def calculate_mean(x, y):
    return (x + y)/2

In [103]:
calculate_mean(7, 9)

8.0

In [117]:
def is_even(number):
    if(number % 2 == 0):
        return True
    else:
        return False
    
def sum_of_even_numbers(numbers):
    running_total = 0
    for number in numbers:
        if(is_even(number)):
            running_total += number
    return running_total

In [109]:
is_even(6)

True

In [122]:
def square(number):
    return number * number

def modify_number(number, modifier_function):
    return modifier_function(number)

modify_number(3, square)

9

In [128]:
def make_price(number):
    return "£" + str(number)

In [129]:
make_price(403)

'£403'

# Libraries

In [130]:
import numpy as np

In [131]:
my_array = np.array([1, 2, 3])

print(my_array )

[1 2 3]


In [132]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])

print(my_2d_array)

[[1 2 3]
 [4 5 6]]


In [133]:
my_array[0]

1

In [137]:
my_2d_array[0, 0]

1

In [138]:
import pandas as pd

In [139]:
france_98_final = {
    "name": ["Barthez", "Thuram", "Leboeuf", "Desailly", "Lizarazu", "Deschamps", "Karembeu", "Petit", "Zidane", "Djorkaeff", "Guivarc'h"],
    "number": [16, 15, 18, 8, 3, 7, 19, 17, 10, 6, 9]
}

france_98_final

{'name': ['Barthez',
  'Thuram',
  'Leboeuf',
  'Desailly',
  'Lizarazu',
  'Deschamps',
  'Karembeu',
  'Petit',
  'Zidane',
  'Djorkaeff',
  "Guivarc'h"],
 'number': [16, 15, 18, 8, 3, 7, 19, 17, 10, 6, 9]}

In [140]:
type(france_98_final)

dict

In [152]:
france_98_final_dataframe = pd.DataFrame(france_98_final)

france_98_final_dataframe

name  number
0     Barthez      16
1      Thuram      15
2     Leboeuf      18
3    Desailly       8
4    Lizarazu       3
5   Deschamps       7
6    Karembeu      19
7       Petit      17
8      Zidane      10
9   Djorkaeff       6
10  Guivarc'h       9

In [142]:
pd.DataFrame?

In [149]:
f98_new_index = range(1, 12)

In [151]:
france_98_final_dataframe.reindex(f98_new_index)

name  number
1      Thuram    15.0
2     Leboeuf    18.0
3    Desailly     8.0
4    Lizarazu     3.0
5   Deschamps     7.0
6    Karembeu    19.0
7       Petit    17.0
8      Zidane    10.0
9   Djorkaeff     6.0
10  Guivarc'h     9.0
11        NaN     NaN

TypeError: 'pandas._libs.properties.AxisProperty' object is not callable